import { ISpecialChacters } from './equation-editor.interfaces';

export const SPECIAL_CHARACTERS = <ISpecialChacters[]>[
  {
    name: 'Dollar sign',
    symbol: '$',
    unicode: 'U+0024',
    category: 'Currency',
  },
  {
    name: 'Single Left-Pointing angle quotation mark',
    symbol: '‹',
    unicode: 'U+2039',
    category: 'Text',
  },
  {
    name: 'Euro Sign',
    symbol: '€',
    unicode: 'U+20AC',
    category: 'Currency',
  },
  {
    name: 'Yen Sign',
    symbol: '¥',
    unicode: 'U+00A5',
    category: 'Currency',
  },
  {
    name: 'Pound Sign',
    symbol: '£',
    unicode: 'U+00A3',
    category: 'Currency',
  },
  {
    name: 'Cent Sign',
    symbol: '¢',
    unicode: 'U+00A2',
    category: 'Currency',
  },
  {
    name: 'Euro-Currency Sign',
    symbol: '₠',
    unicode: 'U+20A0',
    category: 'Currency',
  },
  {
    name: 'Colon Sign',
    symbol: '₡',
    unicode: 'U+20A1',
    category: 'Currency',
  },
  {
    name: 'Cruzeiro Sign',
    symbol: '₢',
    unicode: 'U+20A2',
    category: 'Currency',
  },
  {
    name: 'French Franch Sign',
    symbol: '₣',
    unicode: 'U+20A3',
    category: 'Currency',
  },
  {
    name: 'Lira Sign',
    symbol: '₤',
    unicode: 'U+20B5',
    category: 'Currency',
  },
  {
    name: 'Currency Sign',
    symbol: '¤',
    unicode: 'U+00A4',
    category: 'Currency',
  },
  {
    name: 'Bitcoin Sign',
    symbol: '₿',
    unicode: 'U+20BF',
    category: 'Currency',
  },
  {
    name: 'Mill Sign',
    symbol: '₥',
    unicode: 'U+20A5',
    category: 'Currency',
  },
  {
    name: 'Naira Sign',
    symbol: '₦',
    unicode: 'U+20A6',
    category: 'Currency',
  },
  {
    name: 'Peseta Sign',
    symbol: '₧',
    unicode: 'U+20A7',
    category: 'Currency',
  },
  {
    name: 'Rupee Sign',
    symbol: '₨',
    unicode: 'U+20A8',
    category: 'Currency',
  },
  {
    name: 'Won Sign',
    symbol: '₩',
    unicode: 'U+20A9',
    category: 'Currency',
  },
  {
    name: 'New Sheqel Sign',
    symbol: '₪',
    unicode: 'U+20AA',
    category: 'Currency',
  },
  {
    name: 'Dong Sign',
    symbol: '₫',
    unicode: 'U+20AB',
    category: 'Currency',
  },
  {
    name: 'Kip Sign',
    symbol: '₭',
    unicode: 'U+20AD',
    category: 'Currency',
  },
  {
    name: 'Tugrik Sign',
    symbol: '₮',
    unicode: 'U+20AE',
    category: 'Currency',
  },
  {
    name: 'Drachma Sign',
    symbol: '₯',
    unicode: 'U+20AF',
    category: 'Currency',
  },
  {
    name: 'German Penny Sign',
    symbol: '₰',
    unicode: 'U+20B0',
    category: 'Currency',
  },
  {
    name: 'Peso Sign',
    symbol: '₱',
    unicode: 'U+20B1',
    category: 'Currency',
  },
  {
    name: 'Guarani  Sign',
    symbol: '₲',
    unicode: 'U+20B2',
    category: 'Currency',
  },
  {
    name: 'Austral Sign',
    symbol: '₳',
    unicode: 'U+20B3',
    category: 'Currency',
  },
  {
    name: 'Hryvnia Sign',
    symbol: '₴',
    unicode: 'U+20B4',
    category: 'Currency',
  },
  {
    name: 'Cedi Sign',
    symbol: '₵',
    unicode: 'U+20B5',
    category: 'Currency',
  },
  {
    name: 'Livre Tournois Sign',
    symbol: '₶',
    unicode: 'U+20B6',
    category: 'Currency',
  },
  {
    name: 'Spesmilo Sign',
    symbol: '₷',
    unicode: 'U+20B7',
    category: 'Currency',
  },
  {
    name: 'Tenge Sign',
    symbol: '₸',
    unicode: 'U+20B8',
    category: 'Currency',
  },
  {
    name: 'Indian Rupee Sign',
    symbol: '₹',
    unicode: 'U+20B9',
    category: 'Currency',
  },
  {
    name: 'Turkish Lira Sign',
    symbol: '₺',
    unicode: 'U+20BA',
    category: 'Currency',
  },
  {
    name: 'Nordic Mark Sign',
    symbol: '₻',
    unicode: 'U+20BB',
    category: 'Currency',
  },
  {
    name: 'Manat Sign',
    symbol: '₼',
    unicode: 'U+20BC',
    category: 'Currency',
  },
  {
    name: 'Ruble Sign',
    symbol: '₽',
    unicode: 'U+20BD',
    category: 'Currency',
  },
  {
    name: 'Single Right-Pointing Angle Quotation Mark',
    symbol: '›',
    unicode: 'U+203A',
    category: 'Text',
  },
  {
    name: 'Left-Pointing Double Angle Quotation Mark',
    symbol: '«',
    unicode: 'U+OOAB',
    category: 'Text',
  },
  {
    name: 'Right-Pointing Double Angle Quotation Mark',
    symbol: '»',
    unicode: 'U+OOBB',
    category: 'Text',
  },
  {
    name: 'Left Single Quotation Mark',
    symbol: '‘',
    unicode: 'U+2018',
    category: 'Text',
  },
  {
    name: 'Right Single Quotation Mark',
    symbol: '’',
    unicode: 'U+2019',
    category: 'Text',
  },
  {
    name: 'Left Double Quotation Mark',
    symbol: '“',
    unicode: 'U+201C',
    category: 'Text',
  },
  {
    name: 'Right Double Quotation Mark',
    symbol: '”',
    unicode: 'U+201D',
    category: 'Text',
  },
  {
    name: 'Single Low-9 Quotation Mark',
    symbol: '‚',
    unicode: 'U+201A',
    category: 'Text',
  },
  {
    name: 'Double Low-9 Quotation Mark',
    symbol: '„',
    unicode: 'U+201E',
    category: 'Text',
  },
  {
    name: 'Inverted Exclamation Mark',
    symbol: '¡',
    unicode: 'U+00A1',
    category: 'Text',
  },
  {
    name: 'Inverted Question Mark',
    symbol: '¿',
    unicode: 'U+00BF',
    category: 'Text',
  },
  {
    name: 'Two Dot Leader',
    symbol: '‥',
    unicode: 'U+2025',
    category: 'Text',
  },
  {
    name: 'Horizontal Ellipsis',
    symbol: '…',
    unicode: 'U+2026',
    category: 'Text',
  },
  {
    name: 'Double Dagger',
    symbol: '‡',
    unicode: 'U+2022',
    category: 'Text',
  },
  {
    name: 'Per Mille Sign',
    symbol: '‰',
    unicode: 'U+2030',
    category: 'Text',
  },
  {
    name: 'Per Ten Thousand Sign',
    symbol: '‱',
    unicode: 'U+2031',
    category: 'Text',
  },
  {
    name: 'Double Exclamation Mark',
    symbol: '‼',
    unicode: 'U+203C',
    category: 'Text',
  },
  {
    name: 'Question Exclamation Mark',
    symbol: '⁈',
    unicode: 'U+2048',
    category: 'Text',
  },
  {
    name: 'Exclamation Question Mark',
    symbol: '⁉',
    unicode: 'U+2049',
    category: 'Text',
  },
  {
    name: 'Double Question Mark',
    symbol: '⁇',
    unicode: 'U+2047',
    category: 'Text',
  },
  {
    name: 'Copyright Sign',
    symbol: '©',
    unicode: 'U+00A9',
    category: 'Text',
  },
  {
    name: 'Registered Sign',
    symbol: '®',
    unicode: 'U+00AE',
    category: 'Text',
  },
  {
    name: 'Trade Mark Sign',
    symbol: '™',
    unicode: 'U+2122',
    category: 'Text',
  },
  {
    name: 'Section Sign',
    symbol: '§',
    unicode: 'U+00A7',
    category: 'Text',
  },
  {
    name: 'Paragraph Sign',
    symbol: '¶',
    unicode: 'U+00B6',
    category: 'Text',
  },
  {
    name: 'Reversed Paragraph Sign',
    symbol: '⁋',
    unicode: 'U+204B',
    category: 'Text',
  },
  {
    name: 'Less-than sign',
    symbol: '<',
    unicode: 'U+003C',
    category: 'Mathematical',
  },
  {
    name: 'Greater-than sign',
    symbol: '>',
    unicode: 'U+003E',
    category: 'Mathematical',
  },
  {
    name: 'Less-than or equal to sign',
    symbol: '≤',
    unicode: 'U+2264',
    category: 'Mathematical',
  },
  {
    name: 'Greater-than or equal to sign',
    symbol: '≥',
    unicode: 'U+2265',
    category: 'Mathematical',
  },
  {
    name: 'En dash',
    symbol: '–',
    unicode: 'U+2013',
    category: 'Mathematical',
  },
  {
    name: 'Emm dash',
    symbol: '–',
    unicode: 'U+2014',
    category: 'Mathematical',
  },
  {
    name: 'Macron',
    symbol: '–',
    unicode: 'U+00AF',
    category: 'Mathematical',
  },
  {
    name: 'Overline',
    symbol: '‾',
    unicode: 'U+203E',
    category: 'Mathematical',
  },
  {
    name: 'Degree sign',
    symbol: '°',
    unicode: 'U+00B0',
    category: 'Mathematical',
  },
  {
    name: 'Minus sign',
    symbol: '−',
    unicode: 'U+2212',
    category: 'Mathematical',
  },
  {
    name: 'Plus-minus sign',
    symbol: '±',
    unicode: 'U+00B1',
    category: 'Mathematical',
  },
  {
    name: 'Division sign',
    symbol: '÷',
    unicode: 'U+00F7',
    category: 'Mathematical',
  },
  {
    name: 'Fraction sign',
    symbol: '⁄',
    unicode: 'U+2044',
    category: 'Mathematical',
  },
  {
    name: 'Multiplication sign',
    symbol: '×',
    unicode: 'U+00D7',
    category: 'Mathematical',
  },
  {
    name: 'Latin small letter f with hook',
    symbol: 'ƒ',
    unicode: 'U+0192',
    category: 'Mathematical',
  },
  {
    name: 'Integral',
    symbol: '∫',
    unicode: 'U+222B',
    category: 'Mathematical',
  },
  {
    name: 'N-ARY summation',
    symbol: '∑',
    unicode: 'U+2211',
    category: 'Mathematical',
  },
  {
    name: 'Infinity',
    symbol: '∞',
    unicode: 'U+221E',
    category: 'Mathematical',
  },
  {
    name: 'Square root',
    symbol: '√',
    unicode: 'U+221A',
    category: 'Mathematical',
  },
  {
    name: 'Tilde operator',
    symbol: '∼',
    unicode: 'U+223C',
    category: 'Mathematical',
  },
  {
    name: 'Approximately equal to',
    symbol: '≅',
    unicode: 'U+2245',
    category: 'Mathematical',
  },
  {
    name: 'Almost equal to',
    symbol: '≈',
    unicode: 'U+2248',
    category: 'Mathematical',
  },
  {
    name: 'Not equal to',
    symbol: '≠',
    unicode: 'U+2260',
    category: 'Mathematical',
  },
  {
    name: 'Identical to',
    symbol: '≡',
    unicode: 'U+2261',
    category: 'Mathematical',
  },
  {
    name: 'Element of',
    symbol: '∈',
    unicode: 'U+2208',
    category: 'Mathematical',
  },
  {
    name: 'Not an element of',
    symbol: '∉',
    unicode: 'U+2209',
    category: 'Mathematical',
  },
  {
    name: 'Contains as member',
    symbol: '∋',
    unicode: 'U+220B',
    category: 'Mathematical',
  },
  {
    name: 'N-ARY product',
    symbol: '∏',
    unicode: 'U+220F',
    category: 'Mathematical',
  },
  {
    name: 'Logical AND',
    symbol: '∧',
    unicode: 'U+2227',
    category: 'Mathematical',
  },
  {
    name: 'Logical OR',
    symbol: '∨',
    unicode: 'U+2228',
    category: 'Mathematical',
  },
  {
    name: 'Not sign',
    symbol: '¬',
    unicode: 'U+00AC',
    category: 'Mathematical',
  },
  {
    name: 'Intersection',
    symbol: '∩',
    unicode: 'U+2229',
    category: 'Mathematical',
  },
  {
    name: 'Union',
    symbol: '∪',
    unicode: 'U+222A',
    category: 'Mathematical',
  },
  {
    name: 'Partial Differential',
    symbol: '∂',
    unicode: 'U+2202',
    category: 'Mathematical',
  },
  {
    name: 'For all',
    symbol: '∀',
    unicode: 'U+2200',
    category: 'Mathematical',
  },
  {
    name: 'There exists',
    symbol: '∃',
    unicode: 'U+2203',
    category: 'Mathematical',
  },
  {
    name: 'Empty set',
    symbol: '∅',
    unicode: 'U+2205',
    category: 'Mathematical',
  },
  {
    name: 'Nabla',
    symbol: '∇',
    unicode: 'U+2207',
    category: 'Mathematical',
  },
  {
    name: 'Asterisk operator',
    symbol: '∗',
    unicode: 'U+2217',
    category: 'Mathematical',
  },
  {
    name: 'Proportional to',
    symbol: '∝',
    unicode: 'U+221D',
    category: 'Mathematical',
  },
  {
    name: 'Angle',
    symbol: '∠',
    unicode: 'U+2220',
    category: 'Mathematical',
  },
  {
    name: 'Vulgar fraction one quarter',
    symbol: '¼',
    unicode: 'U+00BC',
    category: 'Mathematical',
  },
  {
    name: 'Vulgar fraction one half',
    symbol: '½',
    unicode: 'U+00BD',
    category: 'Mathematical',
  },
  {
    name: 'Vulgar fraction three quarters',
    symbol: '¾',
    unicode: 'U+00BE',
    category: 'Mathematical',
  },
  {
    name: 'Leftwards Double Arrow',
    symbol: '⇐',
    unicode: 'U+21D0',
    category: 'Arrows',
  },
  {
    name: 'Rightwards Double Arrow',
    symbol: '⇒',
    unicode: 'U+21D2',
    category: 'Arrows',
  },
  {
    name: 'Upwards Double Arrow',
    symbol: '⇑',
    unicode: 'U+21D1',
    category: 'Arrows',
  },
  {
    name: 'Downwards Double Arrow',
    symbol: '⇓',
    unicode: 'U+21D3',
    category: 'Arrows',
  },
  {
    name: 'Leftwards Dashed Arrow',
    symbol: '⇠',
    unicode: 'U+21E0',
    category: 'Arrows',
  },
  {
    name: 'Rightwards Dashed Arrow',
    symbol: '⇢',
    unicode: 'U+21E2',
    category: 'Arrows',
  },
  {
    name: 'Upwards Dashed Arrow',
    symbol: '⇡',
    unicode: 'U+21E1',
    category: 'Arrows',
  },
  {
    name: 'Downwards Dashed Arrow',
    symbol: '⇣',
    unicode: 'U+21E3',
    category: 'Arrows',
  },
  {
    name: 'Leftwards Arrow to bar',
    symbol: '⇤',
    unicode: 'U+21E4',
    category: 'Arrows',
  },
  {
    name: 'Rightwards Arrow to bar',
    symbol: '⇥',
    unicode: 'U+21E5',
    category: 'Arrows',
  },
  {
    name: 'Upwards Arrow to bar',
    symbol: '⤒',
    unicode: 'U+2912',
    category: 'Arrows',
  },
  {
    name: 'Downwards Arrow to bar',
    symbol: '⤓',
    unicode: 'U+2913',
    category: 'Arrows',
  },
  {
    name: 'Up Down Arrow with base',
    symbol: '↨',
    unicode: 'U+21A8',
    category: 'Arrows',
  },
  {
    name: 'Back with leftwards arrow above',
    symbol: '🔙',
    unicode: 'U+F519',
    category: 'Arrows',
  },
  {
    name: 'End with leftwards arrow above',
    symbol: '🔚',
    unicode: 'U+F51A',
    category: 'Arrows',
  },
  {
    name: 'On with Exclamation mark with left right arrow above',
    symbol: '🔛',
    unicode: 'U+F51B',
    category: 'Arrows',
  },
  {
    name: 'Soon with Rightwards arrow above',
    symbol: '🔜',
    unicode: 'U+F51C',
    category: 'Arrows',
  },
  {
    name: 'Top with Upwards arrow above',
    symbol: '🔝',
    unicode: 'U+F51D',
    category: 'Arrows',
  },
  {
    name: 'LATIN CAPITAL LETTER A WITH MACRON',
    symbol: 'Ā',
    unicode: 'U+0100',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER A WITH MACRON',
    symbol: 'ā',
    unicode: 'U+0101',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER A WITH BREVE',
    symbol: 'Ă',
    unicode: 'U+0102',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER A WITH BREVE',
    symbol: 'ă',
    unicode: 'U+0103',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER A WITH OGONEK',
    symbol: 'Ą',
    unicode: 'U+0104',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER A WITH OGONEK',
    symbol: 'ą',
    unicode: 'U+0105',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER C WITH ACUTE',
    symbol: 'Ć',
    unicode: 'U+0106',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER C WITH ACUTE',
    symbol: 'ć',
    unicode: 'U+0107',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER C WITH CIRCUMFLEX',
    symbol: 'Ĉ',
    unicode: 'U+0108',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER C WITH CIRCUMFLEX',
    symbol: 'ĉ',
    unicode: 'U+0109',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER C WITH DOT ABOVE',
    symbol: 'Ċ',
    unicode: 'U+010A',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER C WITH DOT ABOVE',
    symbol: 'ċ',
    unicode: 'U+010B',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER C WITH CARON',
    symbol: 'Č',
    unicode: 'U+010C',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER C WITH CARON',
    symbol: 'č',
    unicode: 'U+010D',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER D WITH CARON',
    symbol: 'Ď',
    unicode: 'U+010E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER D WITH CARON',
    symbol: 'ď',
    unicode: 'U+010F',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER D WITH STROKE',
    symbol: 'Đ',
    unicode: 'U+0110',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER D WITH STROKE',
    symbol: 'đ',
    unicode: 'U+0111',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER E WITH MACRON',
    symbol: 'Ē',
    unicode: 'U+0112',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER E WITH MACRON',
    symbol: 'ē',
    unicode: 'U+0113',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER E WITH BREVE',
    symbol: 'Ĕ',
    unicode: 'U+0114',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER E WITH BREVE',
    symbol: 'ĕ',
    unicode: 'U+0115',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER E WITH DOT ABOVE',
    symbol: 'Ė',
    unicode: 'U+0116',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER E WITH DOT ABOVE',
    symbol: 'ė',
    unicode: 'U+0117',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER E WITH OGONEK',
    symbol: 'Ę',
    unicode: 'U+0118',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER E WITH OGONEK',
    symbol: 'ę',
    unicode: 'U+0119',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER E WITH CARON',
    symbol: 'Ě',
    unicode: 'U+011A',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER E WITH CARON',
    symbol: 'ě',
    unicode: 'U+011B',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER G WITH CIRCUMFLEX',
    symbol: 'Ĝ',
    unicode: 'U+011C',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER G WITH CIRCUMFLEX',
    symbol: 'ĝ',
    unicode: 'U+011D',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER G WITH BREVE',
    symbol: 'Ğ',
    unicode: 'U+011E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER G WITH BREVE',
    symbol: 'ğ',
    unicode: 'U+011F',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER G WITH DOT ABOVE',
    symbol: 'Ġ',
    unicode: 'U+0120',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER G WITH DOT ABOVE',
    symbol: 'ġ',
    unicode: 'U+0121',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER G WITH CEDILLA',
    symbol: 'Ģ',
    unicode: 'U+0122',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER G WITH CEDILLA',
    symbol: 'ģ',
    unicode: 'U+0123',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER H WITH CIRCUMFLEX',
    symbol: 'Ĥ',
    unicode: 'U+0124',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER H WITH CIRCUMFLEX',
    symbol: 'ĥ',
    unicode: 'U+0125',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER H WITH STROKE',
    symbol: 'Ħ',
    unicode: 'U+0126',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER H WITH STROKE',
    symbol: 'ħ',
    unicode: 'U+0127',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER I WITH TILDE',
    symbol: 'Ĩ',
    unicode: 'U+0128',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER I WITH TILDE',
    symbol: 'ĩ',
    unicode: 'U+0129',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER I WITH MACRON',
    symbol: 'Ī',
    unicode: 'U+012A',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER I WITH MACRON',
    symbol: 'ī',
    unicode: 'U+012B',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER I WITH BREVE',
    symbol: 'Ĭ',
    unicode: 'U+012C',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER I WITH BREVE',
    symbol: 'ĭ',
    unicode: 'U+012D',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER I WITH OGONEK',
    symbol: 'Į',
    unicode: 'U+012E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER I WITH OGONEK',
    symbol: 'į',
    unicode: 'U+012F',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER I WITH DOT ABOVE',
    symbol: 'İ',
    unicode: 'U+0130',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER DOTLESS I',
    symbol: 'ı',
    unicode: 'U+0131',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LIGATURE IJ',
    symbol: 'Ĳ',
    unicode: 'U+0132',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LIGATURE IJ',
    symbol: 'ĳ',
    unicode: 'U+0133',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER J WITH CIRCUMFLEX',
    symbol: 'Ĵ',
    unicode: 'U+0134',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER J WITH CIRCUMFLEX',
    symbol: 'ĵ',
    unicode: 'U+0135',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER K WITH CEDILLA',
    symbol: 'Ķ',
    unicode: 'U+0136',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER K WITH CEDILLA',
    symbol: 'ķ',
    unicode: 'U+0137',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER KRA',
    symbol: 'ĸ',
    unicode: 'U+0138',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER L WITH ACUTE',
    symbol: 'Ĺ',
    unicode: 'U+0139',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER L WITH ACUTE',
    symbol: 'ĺ',
    unicode: 'U+013A',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER L WITH CEDILLA',
    symbol: 'Ļ',
    unicode: 'U+013B',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER L WITH CEDILLA',
    symbol: 'ļ',
    unicode: 'U+013C',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER L WITH CARON',
    symbol: 'Ľ',
    unicode: 'U+013D',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER L WITH CARON',
    symbol: 'ľ',
    unicode: 'U+013E',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER L WITH MIDDLE DOT',
    symbol: 'Ŀ',
    unicode: 'U+013F',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER L WITH MIDDLE DOT',
    symbol: 'ŀ',
    unicode: 'U+0140',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER L WITH STROKE',
    symbol: 'Ł',
    unicode: 'U+0141',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER L WITH STROKE',
    symbol: 'ł',
    unicode: 'U+0142',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER N WITH ACUTE',
    symbol: 'Ń',
    unicode: 'U+0143',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER N WITH ACUTE',
    symbol: 'ń',
    unicode: 'U+0144',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER N WITH CEDILLA',
    symbol: 'Ņ',
    unicode: 'U+0145',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER N WITH CEDILLA',
    symbol: 'ņ',
    unicode: 'U+0146',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER N WITH CARON',
    symbol: 'Ň',
    unicode: 'U+0147',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER N WITH CARON',
    symbol: 'ň',
    unicode: 'U+0148',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER N PRECEDED BY APOSTROPHEE',
    symbol: 'ŉ',
    unicode: 'U+0149',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER ENG',
    symbol: 'Ŋ',
    unicode: 'U+014A',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER ENG',
    symbol: 'ŋ',
    unicode: 'U+014B',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER O WITH MACRON',
    symbol: 'Ō',
    unicode: 'U+014C',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER O WITH MACRON',
    symbol: 'ō',
    unicode: 'U+014D',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER O WITH BREVE',
    symbol: 'Ŏ',
    unicode: 'U+014E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER O WITH BREVE',
    symbol: 'ŏ',
    unicode: 'U+014F',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER O WITH DOUBLE ACUTE',
    symbol: 'Ő',
    unicode: 'U+0150',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER O WITH DOUBLE ACUTE',
    symbol: 'ő',
    unicode: 'U+0151',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LIGATURE OE',
    symbol: 'Œ',
    unicode: 'U+0152',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LIGATURE OE',
    symbol: 'œ',
    unicode: 'U+0153',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER R WITH ACUTE',
    symbol: 'Ŕ',
    unicode: 'U+0154',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER R WITH ACUTE',
    symbol: 'ŕ',
    unicode: 'U+0155',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER R WITH CEDILLA',
    symbol: 'Ŗ',
    unicode: 'U+0156',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER R WITH CEDILLA',
    symbol: 'ŗ',
    unicode: 'U+0157',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER R WITH CARON',
    symbol: 'Ř',
    unicode: 'U+0158',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER R WITH CARON',
    symbol: 'ř',
    unicode: 'U+0159',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER S WITH ACUTE',
    symbol: 'Ś',
    unicode: 'U+015A',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER S WITH ACUTE',
    symbol: 'ś',
    unicode: 'U+015B',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER S WITH CIRCUMFLEX',
    symbol: 'Ŝ',
    unicode: 'U+015C',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER S WITH CIRCUMFLEX',
    symbol: 'ŝ',
    unicode: 'U+015D',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER S WITH CEDILLA',
    symbol: 'Ş',
    unicode: 'U+015E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER S WITH CEDILLA',
    symbol: 'ş',
    unicode: 'U+015F',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER S WITH CARON',
    symbol: 'Š',
    unicode: 'U+0160',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER S WITH CARON',
    symbol: 'š',
    unicode: 'U+0161',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER T WITH CEDILLA',
    symbol: 'Ţ',
    unicode: 'U+0162',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER T WITH CEDILLA',
    symbol: 'ţ',
    unicode: 'U+0163',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER T WITH CARON',
    symbol: 'Ť',
    unicode: 'U+0164',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER T WITH CARON',
    symbol: 'ť',
    unicode: 'U+0165',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER T WITH STROKE',
    symbol: 'Ŧ',
    unicode: 'U+0166',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER T WITH STROKE',
    symbol: 'ŧ',
    unicode: 'U+0167',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER U WITH TILDE',
    symbol: 'Ũ',
    unicode: 'U+0168',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER U WITH TILDE',
    symbol: 'ũ',
    unicode: 'U+0169',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER U WITH MACRON',
    symbol: 'Ū',
    unicode: 'U+016A',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER U WITH MACRON',
    symbol: 'ū',
    unicode: 'U+016B',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER U WITH BREVE',
    symbol: 'Ŭ',
    unicode: 'U+016C',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER U WITH BREVE',
    symbol: 'ŭ',
    unicode: 'U+016D',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER U WITH RING ABOVE',
    symbol: 'Ů',
    unicode: 'U+016E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER U WITH RING ABOVE',
    symbol: 'ů',
    unicode: 'U+016F',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER U WITH DOUBLE ACUTE',
    symbol: 'Ű',
    unicode: 'U+0170',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER U WITH DOUBLE ACUTE',
    symbol: 'ű',
    unicode: 'U+0171',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER U WITH OGONEK',
    symbol: 'Ų',
    unicode: 'U+0172',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER U WITH OGONEK',
    symbol: 'ų',
    unicode: 'U+0173',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER W WITH CIRCUMFLEX',
    symbol: 'Ŵ',
    unicode: 'U+0174',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER W WITH CIRCUMFLEX',
    symbol: 'ŵ',
    unicode: 'U+0175',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER Y WITH CIRCUMFLEX',
    symbol: 'Ŷ',
    unicode: 'U+0176',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER Y WITH CIRCUMFLEX',
    symbol: 'ŷ',
    unicode: 'U+0177',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER Y WITH DIAERESIS',
    symbol: 'Ÿ',
    unicode: 'U+0178',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER Z WITH ACUTE',
    symbol: 'Ź',
    unicode: 'U+0179',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER Z WITH ACUTE',
    symbol: 'ź',
    unicode: 'U+017A',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER Z WITH DOT ABOVE',
    symbol: 'Ż',
    unicode: 'U+017B',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER Z WITH DOT ABOVE',
    symbol: 'ż',
    unicode: 'U+017C',
    category: 'Latin',
  },
  {
    name: 'LATIN CAPITAL LETTER Z WITH CARON',
    symbol: 'Ž',
    unicode: 'U+017D',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER Z WITH CARON',
    symbol: 'ž',
    unicode: 'U+017E',
    category: 'Latin',
  },
  {
    name: 'LATIN SMALL LETTER LONG S',
    symbol: 'ſ',
    unicode: 'U+017F',
    category: 'Latin',
  },
];
